#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

COMMIT_MSG_FILE=$1
echo $COMMIT_MSG_FILE

COMMIT_MSG=$(cat $COMMIT_MSG_FILE | tr -d '\n')


PATTERN="test\(\test\/[0-9]+\): |fix\(\fix\/[0-9]+\): |feat\(\feat\/[0-9]+\): |fix\(\feat\/[0-9]+\): |build: |docs: )"


# Check if the commit message matches the pattern
if echo "$COMMIT_MSG" | grep -E "$PATTERN"; then
    echo "Found PATTERN in commit message: $COMMIT_MSG" >&2
    exit 0
else
    echo "Your Commit Message: $COMMIT_MSG" >&2
    echo "Is Invalid!"
    echo "Commit message must begin with one of the following"
    echo " "
    echo "  fix(feature/****): ..."
    echo "  fix(fix/****): ..."
    echo " "
    echo "  feat(feat/****): ..."
    echo " "
    echo "  test(test/****): ..."
    echo " "
    echo "  build: ..."
    echo "  docs: ..."
    echo " "
    exit 1
fi
